require("dotenv").config();

const PORT = process.env.PORT;
const DB_URI = process.env.DB_URI;
const EMAIL_HOST = process.env.SMTP_HOST;
const EMAIL_CLIENT_ID = process.env.EMAIL_CLIENT_ID;
const EMAIL_CLIENT_SECRET = process.env.EMAIL_CLIENT_SECRET;
const EMAIL_CLIENT_REFRESH_TOKEN = process.env.EMAIL_CLIENT_REFRESH_TOKEN;
const EMAIL_CLIENT_ACCESS_TOKEN = process.env.EMAIL_CLIENT_ACCESS_TOKEN;
const OAUTH_REDIRECT_URI = process.env.OAUTH_REDIRECT_URI;
const EMAIL_USER = process.env.EMAIL_USER;
const ACCESS_JWT_SECRET = process.env.ACCESS_JWT_SECRET;
const REFRESH_JWT_SECRET = process.env.REFRESH_JWT_SECRET;
const MAILTRAP_API_KEY = process.env.MAILTRAP_API_KEY;

module.exports = {
  PORT,
  DB_URI,
  EMAIL_HOST,
  EMAIL_CLIENT_ID,
  EMAIL_CLIENT_SECRET,
  EMAIL_CLIENT_REFRESH_TOKEN,
  EMAIL_CLIENT_ACCESS_TOKEN,
  OAUTH_REDIRECT_URI,
  EMAIL_USER,
  ACCESS_JWT_SECRET,
  REFRESH_JWT_SECRET,
};
